'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './navbar/page'
import {usePathname} from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const path  = usePathname();
  // console.log(path);
  const x = path.split('/')[2]
  // console.log(x);


  return (
    <html lang="en">

{/* {(() => {
      if ( path !== "/driver/"+x){
          return (
            <Navbar></Navbar>
          )
      } 
      else  if ( path !== "/login/"){
        return (        
          <Navbar></Navbar>
      )
      }
      else  if ( path !== "/product"){
        return (        
          <Navbar></Navbar>
      )
      }
      
      return null;
    })()} */}
      <body className={inter.className}>{children}</body>
      {/* {
        path !== "/driver/"+x ? <Navbar></Navbar> :null
    }
     {
        path !== "/login" ? <Navbar></Navbar> :null
    } */}
      {/* <Navbar></Navbar> */}
    </html>
  )
}
